apiVersion: v1
kind: PersistentVolume

metadata:
  name: mongodb-pv

spec:
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /data/mongodb
  persistentVolumeReclaimPolicy: Retain
