apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler

metadata:
  name: easyshop-hpa
  namespace: easyshop

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: easyshop # This should match the name of the deployment
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50 # This is the target CPU utilization percentage
