apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: easyshop-vpa
  namespace: easyshop
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: mongodb
  updatePolicy:
    updateMode: "Auto" # Options: "Off", "Initial", "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: mongodb
      minAllowed:
        cpu: 100m
        memory: 128Mi
      maxAllowed:
        cpu: 1000m
        memory: 1Gi
      controlledResources: [ "cpu", "memory" ]
      controlledValues: RequestsAndLimits
